# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [8]:
import pandas as pd
import numpy as np

### Step 2. Create 3 differents Series, each of length 100, as follows: 
1. The first a random number from 1 to 4 
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [9]:
serie1 = pd.Series(np.random.randint(1,5,size=100))
serie1

0     3
1     1
2     1
3     3
4     1
     ..
95    3
96    4
97    2
98    3
99    4
Length: 100, dtype: int32

In [10]:
serie2 = pd.Series(np.random.randint(1,4,size=100))
serie2

0     1
1     1
2     3
3     2
4     1
     ..
95    2
96    1
97    3
98    3
99    1
Length: 100, dtype: int32

In [11]:
serie3 = pd.Series(np.random.randint(10000,30001,size=100))
serie3

0     14634
1     18549
2     20055
3     28688
4     10533
      ...
95    22931
96    16728
97    22106
98    22744
99    20899
Length: 100, dtype: int32

### Step 3. Let's create a DataFrame by joinning the Series by column

In [ ]:
df=pd.DataFrame([])
df=pd.concat([serie1,serie2,serie3],axis=1)
df

    0  1      2
0   3  1  14634
1   1  1  18549
2   1  3  20055
3   3  2  28688
4   1  1  10533
.. .. ..    ...
95  3  2  22931
96  4  1  16728
97  2  3  22106
98  3  3  22744
99  4  1  20899

[100 rows x 3 columns]

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [18]:
df.columns=["bedrs","bathrs","price_sqr_meter"]
df

    bedrs  bathrs  price_sqr_meter
0       3       1            14634
1       1       1            18549
2       1       3            20055
3       3       2            28688
4       1       1            10533
..    ...     ...              ...
95      3       2            22931
96      4       1            16728
97      2       3            22106
98      3       3            22744
99      4       1            20899

[100 rows x 3 columns]

### Step 5. Create a column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [20]:
bigcolumn=pd.concat([serie1,serie2,serie3],axis=0)
bigcolumn

0         3
1         1
2         1
3         3
4         1
      ...
95    22931
96    16728
97    22106
98    22744
99    20899
Length: 300, dtype: int32

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [21]:
print(bigcolumn)

0         3
1         1
2         1
3         3
4         1
      ...
95    22931
96    16728
97    22106
98    22744
99    20899
Length: 300, dtype: int32

In [22]:
bigcolumn.shape[0]

300

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [23]:
pd.DataFrame(bigcolumn).reset_index()

     index      0
0        0      3
1        1      1
2        2      1
3        3      3
4        4      1
..     ...    ...
295     95  22931
296     96  16728
297     97  22106
298     98  22744
299     99  20899

[300 rows x 2 columns]