# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Create 3 differents Series, each of length 100, as follows: 
1. The first a random number from 1 to 4 
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [2]:
serie1 = pd.Series(np.random.randint(1,5,size=100))
serie1

0     4
1     1
2     1
3     4
4     4
     ..
95    2
96    1
97    4
98    3
99    4
Length: 100, dtype: int32

In [3]:
serie2 = pd.Series(np.random.randint(1,4,size=100))
serie2

0     3
1     3
2     2
3     2
4     2
     ..
95    2
96    1
97    3
98    1
99    3
Length: 100, dtype: int32

In [4]:
serie3 = pd.Series(np.random.randint(10000,30001,size=100))
serie3

0     12307
1     15901
2     18733
3     18372
4     26338
      ...
95    26887
96    15584
97    14602
98    11133
99    10931
Length: 100, dtype: int32

### Step 3. Let's create a DataFrame by joinning the Series by column

In [5]:
df=pd.DataFrame([])
df=pd.concat([serie1,serie2,serie3],axis=1)
df

    0  1      2
0   4  3  12307
1   1  3  15901
2   1  2  18733
3   4  2  18372
4   4  2  26338
.. .. ..    ...
95  2  2  26887
96  1  1  15584
97  4  3  14602
98  3  1  11133
99  4  3  10931

[100 rows x 3 columns]

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [6]:
df.columns=["bedrs","bathrs","price_sqr_meter"]
df

    bedrs  bathrs  price_sqr_meter
0       4       3            12307
1       1       3            15901
2       1       2            18733
3       4       2            18372
4       4       2            26338
..    ...     ...              ...
95      2       2            26887
96      1       1            15584
97      4       3            14602
98      3       1            11133
99      4       3            10931

[100 rows x 3 columns]

### Step 5. Create a column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [7]:
bigcolumn=pd.concat([serie1,serie2,serie3],axis=0)
bigcolumn

0         4
1         1
2         1
3         4
4         4
      ...
95    26887
96    15584
97    14602
98    11133
99    10931
Length: 300, dtype: int32

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [8]:
print(bigcolumn)

0         4
1         1
2         1
3         4
4         4
      ...
95    26887
96    15584
97    14602
98    11133
99    10931
Length: 300, dtype: int32

In [9]:
bigcolumn.shape[0]

300

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [11]:
pd.DataFrame(bigcolumn).reset_index(drop=True)

         0
0        4
1        1
2        1
3        4
4        4
..     ...
295  26887
296  15584
297  14602
298  11133
299  10931

[300 rows x 1 columns]