# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv",sep="\t")
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 3. Assign it to a variable called chipo.

In [3]:
chipo=df
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

# Name of the max valued product

In [4]:
chipo["item_price"]=chipo["item_price"].str.replace("$","").astype(float)
chipo.loc[chipo["item_price"].idxmax(),"item_name"]

'Chips and Fresh Tomato Salsa'

### Step 4. How many products cost more than $10.00?

In [5]:
(chipo["item_price"]>10).sum()

np.int64(1130)

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [6]:
chipo[["item_price","item_name"]]

      item_price                              item_name
0           2.39           Chips and Fresh Tomato Salsa
1           3.39                                   Izze
2           3.39                       Nantucket Nectar
3           2.39  Chips and Tomatillo-Green Chili Salsa
4          16.98                           Chicken Bowl
...          ...                                    ...
4617       11.75                          Steak Burrito
4618       11.75                          Steak Burrito
4619       11.25                     Chicken Salad Bowl
4620        8.75                     Chicken Salad Bowl
4621        8.75                     Chicken Salad Bowl

[4622 rows x 2 columns]

### Step 6. Sort by the name of the item

In [7]:
chipo.sort_values("item_name")

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49
...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

V1

In [8]:
chipo[["quantity"]].max()

quantity    15
dtype: int64

V2

In [9]:
chipo["quantity"].max()

np.int64(15)

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [10]:
(chipo[["item_name"]]=="Veggie Salad Bowl").sum()

item_name    18
dtype: int64

### Step 9. How many times did someone order more than one Canned Soda?

In [ ]:
((chipo["item_name"]=="Canned Soda")&(chipo["quantity"]>1)).sum()

np.int64(20)

In [12]:
chipo[(chipo["item_name"]=="Canned Soda")&(chipo["quantity"]>1)]

      order_id  quantity    item_name choice_description  item_price
18           9         2  Canned Soda           [Sprite]        2.18
51          23         2  Canned Soda     [Mountain Dew]        2.18
162         73         2  Canned Soda        [Diet Coke]        2.18
171         76         2  Canned Soda  [Diet Dr. Pepper]        2.18
350        150         2  Canned Soda        [Diet Coke]        2.18
352        151         2  Canned Soda        [Coca Cola]        2.18
698        287         2  Canned Soda        [Coca Cola]        2.18
700        288         2  Canned Soda        [Coca Cola]        2.18
909        376         2  Canned Soda     [Mountain Dew]        2.18
1091       450         2  Canned Soda       [Dr. Pepper]        2.18
1092       450         2  Canned Soda        [Coca Cola]        2.18
1944       787         2  Canned Soda       [Dr. Pepper]        2.18
2135       859         2  Canned Soda        [Diet Coke]        2.18
2235       901         4  Canned Soda           [Sprite]        4.36
2905      1156         2  Canned Soda        [Coca Cola]        2.18
2906      1156         2  Canned Soda           [Sprite]        2.18
3152      1258         2  Canned Soda       [Dr. Pepper]        2.18
3364      1349         2  Canned Soda        [Coca Cola]        2.18
3592      1440         2  Canned Soda        [Diet Coke]        2.18
3866      1550         2  Canned Soda     [Mountain Dew]        2.18