# Ex3 - Getting and Knowing your Data



### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user",sep="|")
df

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [3]:
users=df.set_index("user_id")
users=pd.DataFrame(users)
users

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
...      ...    ...            ...      ...
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

[943 rows x 4 columns]

### Step 4. See the first 25 entries
Solve it by 2 different ways

In [39]:
users[:25]

         age gender     occupation zip_code
user_id
0         24      M     technician    85711
1         53      F          other    94043
2         23      M         writer    32067
3         24      M     technician    43537
4         33      F          other    15213
5         42      M      executive    98101
6         57      M  administrator    91344
7         36      M  administrator    05201
8         29      M        student    01002
9         53      M         lawyer    90703
10        39      F          other    30329
11        28      F          other    06405
12        47      M       educator    29206
13        45      M      scientist    55106
14        49      F       educator    97301
15        21      M  entertainment    10309
16        30      M     programmer    06355
17        35      F          other    37212
18        40      M      librarian    02138
19        42      F      homemaker    95660
20        26      M         writer    30068
21        25      M         writer    40206
22        30      F         artist    48197
23        21      F         artist    94533
24        39      M       engineer    55107

### Step 5. See the last 10 entries

In [40]:
users[-10:]

         age gender     occupation zip_code
user_id
933       61      M       engineer    22902
934       42      M         doctor    66221
935       24      M          other    32789
936       48      M       educator    98072
937       38      F     technician    55038
938       26      F        student    33319
939       32      M  administrator    02215
940       20      M        student    97229
941       48      F      librarian    78209
942       22      M        student    77841

### Step 6. What is the number of observations in the dataset?
Solve it by 2 different ways

<class 'pandas.core.frame.DataFrame'>
Int64Index: 943 entries, 1 to 943
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         943 non-null    int64
 1   gender      943 non-null    object
 2   occupation  943 non-null    object
 3   zip_code    943 non-null    object
dtypes: int64(1), object(3)
memory usage: 69.1+ KB

In [41]:
print(len(users))

943

In [42]:
print(users.count())

age           943
gender        943
occupation    943
zip_code      943
dtype: int64

In [43]:
print(df.shape[0])

943

### Step 7. What is the number of columns in the dataset?
Solve it by 2 different ways

In [44]:
print(df.shape[1])

5

In [45]:
print(len(users.columns))

4

In [46]:
print(df.columns.size)

5

In [47]:
print(len(users.count()))

4

<class 'pandas.core.frame.DataFrame'>
Int64Index: 943 entries, 1 to 943
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         943 non-null    int64
 1   gender      943 non-null    object
 2   occupation  943 non-null    object
 3   zip_code    943 non-null    object
dtypes: int64(1), object(3)
memory usage: 69.1+ KB

### Step 8. Print the name of all the columns.

In [ ]:
# cada nombre de la columna en una linea sin for ???
print(users.head(0))

Empty DataFrame
Columns: [age, gender, occupation, zip_code]
Index: []

In [49]:
users.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='str')

### Step 9. How is the dataset indexed? Get the index values

In [74]:
users.index

RangeIndex(start=0, stop=943, step=1, name='user_id')

### Step 10. What is the data type of each column?
Solve it by 2 different ways

In [56]:
users.dtypes

age           int64
gender          str
occupation      str
zip_code        str
dtype: object

<class 'pandas.core.frame.DataFrame'>
Int64Index: 943 entries, 1 to 943
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         943 non-null    int64
 1   gender      943 non-null    object
 2   occupation  943 non-null    object
 3   zip_code    943 non-null    object
dtypes: int64(1), object(3)
memory usage: 69.1+ KB

### Step 11. Print only the occupation column
Solve it by 2 different ways

In [ ]:
users[["occupation"]]

users.loc[:]["occupation"]

users.loc[:,["occupation"]]

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: str

In [88]:
users.occupation

user_id
0         technician
1              other
2             writer
3         technician
4              other
           ...
938          student
939    administrator
940          student
941        librarian
942          student
Name: occupation, Length: 943, dtype: str

In [84]:
users.iloc[500]

age                22
gender              M
occupation    student
zip_code        10025
Name: 500, dtype: object

### Step 12. How many different occupations are in this dataset? How many users per occupation are in the dataset?

In [ ]:
users.occupation.unique()

<StringArray>
[   'technician',         'other',        'writer',     'executive',
 'administrator',       'student',        'lawyer',      'educator',
     'scientist', 'entertainment',    'programmer',     'librarian',
     'homemaker',        'artist',      'engineer',     'marketing',
          'none',    'healthcare',       'retired',      'salesman',
        'doctor']
Length: 21, dtype: str

In [98]:
users.occupation.nunique()

21

In [97]:
users.occupation.value_counts()

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
homemaker          7
doctor             7
Name: count, dtype: int64

### Step 13. What is the most frequent occupation?

In [100]:
users.occupation.value_counts().idxmax()

'student'

### Step 14. Summarize the DataFrame.

In [114]:
users.describe()

              age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

### Step 15. Summarize all the columns

In [101]:
users.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='str')

In [115]:
users.describe(include="all")

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

### Step 16. Summarize only the occupation column

In [112]:
users.occupation.describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### Step 17. What is the mean age of users?

In [116]:
users.age.mean()

np.float64(34.05196182396607)

### Step 18. What is the age with least occurrence?

In [ ]:
users["age"].value_counts().idxmin()

np.int64(7)

In [ ]:
users["age"].value_counts().sort_values()

np.int64(1)

7     1
66    1
11    1
10    1
73    1
Name: age, dtype: int64

         age gender occupation zip_code
user_id
30         7      M    student    55436
211       66      M   salesman    32605
289       11      M       none    94619
471       10      M    student    77459
481       73      M    retired    37771

70    3
62    2
68    2
64    2
69    2
7     1
66    1
11    1
10    1
73    1
Name: age, dtype: int64